spring:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver

server:
  port: 8090
logging:
  level:
    com: DEBUG
    org: DEBUG
      #hibernate:
        #SQL: DEBUG
        #type:
          #descriptor:
           # sql:
              #BasicBinder: TRACE
graphql:
  servlet:
    mapping: /graphql
